language: node_js
node_js:
  - "node"

cache:
  directories:
    - "node_modules"

deploy:
  provider: heroku
  api_key:
    secure: nbdDvyU45adZlZu5nwiuvecCup1OtbYxzscugbdXiT/A+diTkzxmSkLaUDiSZfE8faWDA+HyJ4HcKSUK73QqahjL82dM6cPI/wrgp9N/bVzI3E9cn4uFGGgWiHTjnWQUwaBQJNUHJ9X8h/3t0u/W+Ne7d3YgAaD+vjHE4+ArOmNMHnsWnn5oisMZ/la6J2yzOznejyZqkynDmOSir6oV4BXaAl64bmt/oN6SFB+BphbyTgtJFDqcPwajL+UxCrC34oUA0aXz78bWymMEZutPfcXhpixw5nFRY3FH3FgzYGgIaOIh28WCI8kEuHcnEax5GwL884cLEX4oyvyfdQIUZIl4clJ7/RvBREbTnwJFZqMES9c1GHz9eM2b+Op3H7DPxTDpOtEgImq4/Fyi/bt3srTI0tkPj0UBoLObZ5BoFjvtr0YobDdPhXjwVtAmEAO6OGUJAaPltTK9xuMdcvWfyVhI/IqhXXFc4+nqZ+Wgr1+d5ibmaLlb/ys/SY2oMbSLIDe8wpM7T2CzeW7mBXgNq6dYzARcg7eC2ZHk2cBRwqeGrQ8XOiZLN4qBqjjhyqaqfO2+LdQYkil9h6brTthCo6CXtb/z9GRX6g4ayojPissr6YjqnDsMisOTY5t/srSyczPTD0FfezrNoMVw3145uZH0xJZtHr1NGqm7WHNIy+8=
