language: node_js
node_js:
- node
cache:
  directories:
  - node_modules
deploy:
  provider: heroku
  api_key:
    secure: p8s7TqTrF5fzPu0CLHg/V00v8mxhdyglMPzNnbkN2EMbE8+y/yO/mY/dwx5miZdBhQa6xaaU7bsEvCZ/SD0EphrA2NiCX6lF1m0ivEWaMki4x39ZcNOBpI2XK+iWGo5972t7oiNwwP68fHgEsZiGw8J5LK4p3UAxo72pZU5Mb/QXQU14NfHqfJQIcK2YJ2NE2pP5kE0QjWTr+WkPxvKYD/mcW5EJjKCmwY23/7xnaGdvnbJGSztyqXx7Gk3eMApzyjBib9reyw0LbZfQsgoCWEmi/gqBmPw0Qau0WP/XrNqRo09pIOPyEmHjL6+vDu/v/w9yGEOJFG0Fh3dmcTuIh9B6cdeWxaNizVQGvCGHDbuYZVYXxiYIjH3wrY8BSybNgZcFw7JatHL4ycHyndKegaW18looa2tOw9ysN0Y4rhKOuR3W6yxdLk4I4KWb4E1guuLLf0b4sqidw1JhU3TL7r23CzN3+pRGj5qQZw6MmFkYe2TdoKwD0w3k8ejQY1pTlex4lpIbeEJxNwbTAN8ufKO4sl/c0z9qcTchqzlz/oVlRAqgZuceSacpYXpkwYZgwVFOlGedP5mcUEUgNpV4bEIIxTUw/WbxBh12/gasZJ2xRS2lQAPWl+78VZFUC1jnlTKmZumJRxyN8sYVF4nICHYabELu9Y+Pt8fdL86W8KQ=
