language: node_js
node_js:
- node
cache:
  directories:
  - node_modules
deploy:
  provider: heroku
  api_key:
    secure: aX5ZKekwJZa92WgUvfTAOWIZS2yBiFePuL7Py4k9eiADWz6g+a1CNCyU+DHLanq0ZRyPxMJb8P92SwsuWXUk67vYY1gxQnsoaHyLEBCQ3UcROBw8gDvViWHH2pS+m0NEjgTUKtK2wjolZ7MG4M4TcN6q5zJsf/oLg65fjAhWWuCoQU0B4JLCGtnL1xeVZYmBN+lLc8k7Je/t+Pu2pgLMggWD7R50RKgGDA5BmBC68Lb4houPp36UM+ZP3FoNinZD+TUcIQ8oFh8u6P3wYQjv78ZXgRoDm4Gmst0d8216gwQPcWs4ijbX6pCMie7ZF60zldwfMZhSnFDz4vvH/mMcEvGq1SyuknkhmndBEeeeAmAv6jPeGKcjL7HKD6iFo/AqKJY1cejmUbkKutNtMmZTHaVbFA/sD95Utmp3QhtGWBA6V+k6E9ezv0/MXUzOA21FAp3Di6j0zSdrcM6DUfi9l8chqOHWajrC1UxdTjVHp5vVDvsDXnj68xnvesdCdpE7bhvy8sMONATrJfxuRLpS1yGIGDZhQqhhNwipiPvrozHETqxSnsTXb0hNRmC+kJuO6qORu0MgXtwgyGoySkzeofrt9Bdr4usjQggpxaHN2Zf4LQlLZDfOZwyQS9zMV735rMTIK2NtfAvsAC8EdzgUOcLG9HoxT4Kw/InN++4Jsrw=
  app: secret-depths-69125